# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Separar los telefonos mediante: |', max_length=120, verbose_name='Tel\xe9fono')),
                ('correos', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=120, verbose_name='Direcci\xf3n')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad - Distrito')),
                ('mapa', geoposition.fields.GeopositionField(max_length=42)),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosotros', models.TextField(verbose_name='Descripci\xf3n')),
                ('nosotros_image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Imagen Productos')),
                ('servicios', models.TextField(verbose_name='Descripci\xf3n')),
                ('servicios_image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Imagen Productos')),
                ('vehiculos', models.TextField(verbose_name='Descripci\xf3n')),
                ('vehiculos_image', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Imagen Productos')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Imagen Productos')),
                ('titulo', models.CharField(max_length=60, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=60, verbose_name='Sub-Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
            },
        ),
    ]
