# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(help_text='Separar los telefonos mediante: |', max_length=120, verbose_name='Tel\xe9fono')),
                ('correos', models.EmailField(max_length=254, verbose_name='Correo')),
                ('direccion', models.CharField(max_length=120, verbose_name='Direcci\xf3n')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad - Distrito')),
                ('mapa', geoposition.fields.GeopositionField(max_length=42)),
            ],
            options={
                'verbose_name': 'Configuracion',
                'verbose_name_plural': 'Configuracions',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosotros', models.TextField(verbose_name='Descripci\xf3n')),
                ('nosotros_image', models.ImageField(upload_to='nosotros_image', verbose_name='Imagen')),
                ('servicios', models.TextField(verbose_name='Descripci\xf3n')),
                ('servicios_image', models.ImageField(upload_to='servicios_image', verbose_name='Imagen')),
                ('vehiculos', models.TextField(verbose_name='Descripci\xf3n')),
                ('vehiculos_image', models.ImageField(upload_to='vehiculos_image', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Homes',
            },
        ),
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banner', verbose_name='Banner')),
                ('titulo', models.CharField(max_length=60, verbose_name='Titulo')),
                ('subtitulo', models.CharField(max_length=60, verbose_name='Sub-Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'HomeBanner',
                'verbose_name_plural': 'HomeBanners',
            },
        ),
    ]
