# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contacto',
            },
        ),
        migrations.CreateModel(
            name='MovilizarEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('Correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Movilizar a tu Empresa',
                'verbose_name_plural': 'Movilizar a tu Empresas',
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosotros_amarillo', models.TextField(verbose_name='Nosotros texto amarillo')),
                ('nosotros_plomo', models.TextField(verbose_name='Nosotros texto plomo')),
                ('banner', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Banner')),
                ('mision', models.TextField(verbose_name='Misi\xf3n')),
                ('vision', models.TextField(verbose_name='Visi\xf3n')),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotross',
            },
        ),
        migrations.CreateModel(
            name='NuestrosServicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posicion')),
                ('imagen', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Servicios')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'Valores',
                'verbose_name_plural': 'Valoress',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Servicios Banner')),
            ],
            options={
                'verbose_name': 'Nosotros',
                'verbose_name_plural': 'Nosotross',
            },
        ),
        migrations.CreateModel(
            name='Valores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posicion')),
                ('imagen', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Valores')),
                ('titulo', models.CharField(max_length=120, verbose_name='Titulo')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
                ('nosotros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nosotros_valores', to='web.Nosotros')),
            ],
            options={
                'verbose_name': 'Valores',
                'verbose_name_plural': 'Valoress',
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.IntegerField(default=0, verbose_name='Posicion')),
                ('vehiculo', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Vehiculos Imagen')),
                ('descripcion', models.TextField(verbose_name='Descripci\xf3n')),
            ],
            options={
                'verbose_name': 'Vehiculos',
                'verbose_name_plural': 'Vehiculoss',
            },
        ),
        migrations.AlterField(
            model_name='home',
            name='nosotros_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Nosostros Imagen'),
        ),
        migrations.AlterField(
            model_name='home',
            name='servicios_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Servicios Imagen'),
        ),
        migrations.AlterField(
            model_name='home',
            name='vehiculos_image',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Vehiculos Imagen'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='banner',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Home Banner'),
        ),
        migrations.AddField(
            model_name='nuestrosservicios',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_valores', to='web.Servicios'),
        ),
    ]
