# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracion',
            options={'verbose_name': 'Configuracion', 'verbose_name_plural': 'Configuraciones'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Home', 'verbose_name_plural': 'Home'},
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'verbose_name': 'Home Banner', 'verbose_name_plural': 'Home Banners'},
        ),
    ]
