# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160913_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default='2015-12-12 11:11:11', verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movilizarempresa',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default='2015-12-12 11:11:11', verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valores',
            name='imagen',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Imagen'),
        ),
    ]
