# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 18:31
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160911_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='nosotros_image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nosotros_image', to='filer.Image'),
        ),
    ]
