# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-11 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160911_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
