# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160913_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='posicion',
            field=models.IntegerField(default=0, verbose_name='Posicion'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='homebanner',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=60, verbose_name='Sub-Titulo'),
        ),
    ]
