# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-13 17:42
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20160913_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='nosotros',
            name='image',
            field=filebrowser.fields.FileBrowseField(default='', max_length=200, verbose_name='Banner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nosotros',
            name='banner',
            field=filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Nosotros Banner'),
        ),
    ]
