# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0006_auto_20160623_1627'),
        ('web', '0005_auto_20160911_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='imagen_fondo_amarillo',
            field=filer.fields.image.FilerImageField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fondo_amarillo', to=b'filer.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='imagen_fondo_negro',
            field=filer.fields.image.FilerImageField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='fondo_negro', to=b'filer.Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='texto_fondo_amarillo',
            field=models.CharField(default='', help_text='Separar los textos mediante: |', max_length=120, verbose_name='Texto Fondo Amarillo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='texto_fondo_negro',
            field=models.CharField(default='', help_text='Separar los textos mediante: |', max_length=120, verbose_name='Texto Fondo Negro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='home',
            name='nosotros_image',
            field=filer.fields.image.FilerImageField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='nosotros_image', to=b'filer.Image', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='servicios_image',
            field=filer.fields.image.FilerImageField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_image', to=b'filer.Image', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='vehiculos_image',
            field=filer.fields.image.FilerImageField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos_image', to=b'filer.Image', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
