# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20160911_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='imagen_fondo_amarillo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='imagen_fondo_negro',
        ),
        migrations.RemoveField(
            model_name='home',
            name='texto_fondo_amarillo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='texto_fondo_negro',
        ),
    ]
