# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-14 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20160913_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', filebrowser.fields.FileBrowseField(max_length=200, verbose_name='Vehiculo Banner')),
            ],
            options={
                'verbose_name': 'ContactoBanner',
                'verbose_name_plural': 'ContactoBanners',
            },
        ),
    ]
