# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-15 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20160915_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='mensaje_gracias',
            field=models.TextField(default='', verbose_name='Mensaje de Gracias'),
            preserve_default=False,
        ),
    ]
