# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-16 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_configuracion_mensaje_gracias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movilizarempresa',
            old_name='Correo',
            new_name='correo',
        ),
    ]
